baseurl = "/"
title = "Ryan Thomas"
copyright = "Copyright &copy; 2019 - Ryan Thomas"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false
pygmentsUseClasses = false

[author]
    name = "Ryan Thomas"
    github = "actuarialvoodoo"
    gitlab = ""
    linkedin = "ryan-thomas-5387028"
    facebook = ""
    twitter = "ryebreadnyc"
    instagram = ""

[params]
    tagline = "Actuary. Nerd. Data Scientist?"
    
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "sql"]
    highlightjsTheme = "hopscotch"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"