baseurl = "https://www.ryanthomasr.com/"
title = "Ryan Thomas"
copyright = "Copyright &copy; 2019 - Ryan Thomas"
canonifyurls = true
theme = "hugo-kiera"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "post_data$"]
paginate = 3
#menu = "main"
#meta = "false"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = false
pygmentsUseClasses = false
#sectionPagesMenu = "Slides"

[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = -100


[author]
    name = "Ryan Thomas"
    github = "actuarialvoodoo"
    gitlab = ""
    linkedin = "ryan-thomas-5387028"
    facebook = ""
    twitter = "ryebreadnyc"
    instagram = ""

[params]
    tagline = "Actuary. Nerd. Data Scientist?"
    
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "https://cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "sql"]
    highlightjsTheme = "hopscotch"

    MathJaxCDN = "https://cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
